services:
  web:
    build: .
    container_name: rails-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s
    # -c付けると失敗しても続けるだっけ？
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
  db:
    image: mysql:8.0
    container_name: rails-mysql
    # volumes:
    #   - mysql_data:/var/lib/mysql/
      # - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_docker_mysql_development
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8888:80
# volumes:
#   mysql_data:
            
